// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewsSummarizer.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NewsSummarizer.Infrastructure.Migrations
{
    [DbContext(typeof(NewsSummarizerDbContext))]
    [Migration("20260517061129_SyncArticleEmbeddingsModel_20260517091122")]
    partial class SyncArticleEmbeddingsModel_20260517091122
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NewsSummarizer.Core.Entities.ArticleAiResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("DailyDigestCandidate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("daily_digest_candidate");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<int>("ImportanceScore")
                        .HasColumnType("integer")
                        .HasColumnName("importance_score");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("model");

                    b.Property<bool>("OpportunityDigestCandidate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("opportunity_digest_candidate");

                    b.Property<string>("OpportunityReason")
                        .HasColumnType("text")
                        .HasColumnName("opportunity_reason");

                    b.Property<int>("OpportunityScore")
                        .HasColumnType("integer")
                        .HasColumnName("opportunity_score");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("RawResponseJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_response");

                    b.Property<string>("Reason")
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("UrgencyScore")
                        .HasColumnType("integer")
                        .HasColumnName("urgency_score");

                    b.Property<bool>("UrgentCandidate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("urgent_candidate");

                    b.HasKey("Id")
                        .HasName("pk_article_ai_results");

                    b.HasIndex("ArticleId")
                        .HasDatabaseName("ix_article_ai_results_article_id");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_article_ai_results_category");

                    b.HasIndex("DailyDigestCandidate")
                        .HasDatabaseName("ix_article_ai_results_daily_digest_candidate");

                    b.HasIndex("ImportanceScore")
                        .HasDatabaseName("ix_article_ai_results_importance_score");

                    b.HasIndex("OpportunityDigestCandidate")
                        .HasDatabaseName("ix_article_ai_results_opportunity_digest_candidate");

                    b.HasIndex("OpportunityScore")
                        .HasDatabaseName("ix_article_ai_results_opportunity_score");

                    b.HasIndex("UrgencyScore")
                        .HasDatabaseName("ix_article_ai_results_urgency_score");

                    b.HasIndex("UrgentCandidate")
                        .HasDatabaseName("ix_article_ai_results_urgent_candidate");

                    b.HasIndex("ArticleId", "Provider", "PromptVersion")
                        .IsUnique()
                        .HasDatabaseName("ix_article_ai_results_article_id_provider_prompt_version");

                    b.ToTable("article_ai_results", null, t =>
                        {
                            t.HasCheckConstraint("ck_article_ai_results_importance_score_range", "importance_score >= 0 AND importance_score <= 100");

                            t.HasCheckConstraint("ck_article_ai_results_opportunity_score_range", "opportunity_score >= 0 AND opportunity_score <= 100");

                            t.HasCheckConstraint("ck_article_ai_results_urgency_score_range", "urgency_score >= 0 AND urgency_score <= 100");
                        });
                });

            modelBuilder.Entity("NewsSummarizer.Core.Entities.ArticleEmbedding", b =>
                {
                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Dimensions")
                        .HasColumnType("integer")
                        .HasColumnName("dimensions");

                    b.PrimitiveCollection<float[]>("Embedding")
                        .IsRequired()
                        .HasColumnType("real[]")
                        .HasColumnName("embedding");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("model");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("TextHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("text_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ArticleId")
                        .HasName("pk_article_embeddings");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_article_embeddings_created_at");

                    b.HasIndex("Model")
                        .HasDatabaseName("ix_article_embeddings_model");

                    b.HasIndex("Provider")
                        .HasDatabaseName("ix_article_embeddings_provider");

                    b.HasIndex("TextHash")
                        .HasDatabaseName("ix_article_embeddings_text_hash");

                    b.ToTable("article_embeddings", (string)null);
                });

            modelBuilder.Entity("NewsSummarizer.Core.Entities.DetailedAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnalysisText")
                        .HasColumnType("text")
                        .HasColumnName("analysis_text");

                    b.Property<Guid?>("ArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("model");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("prompt_version");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<string>("RawResponseJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("raw_response");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_detailed_analyses");

                    b.HasIndex("ArticleId")
                        .HasDatabaseName("ix_detailed_analyses_article_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_detailed_analyses_expires_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_detailed_analyses_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_detailed_analyses_user_id");

                    b.ToTable("detailed_analyses", (string)null);
                });

            modelBuilder.Entity("NewsSummarizer.Core.Entities.Digest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DigestType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("digest_type");

                    b.Property<DateTimeOffset>("PeriodEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_end");

                    b.Property<DateTimeOffset>("PeriodStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("period_start");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Created")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_digests");

                    b.HasIndex("DigestType")
                        .HasDatabaseName("ix_digests_digest_type");

                    b.HasIndex("SentAt")
                        .HasDatabaseName("ix_digests_sent_at");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_digests_status");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_digests_user_id");

                    b.HasIndex("UserId", "DigestType", "PeriodStart", "PeriodEnd")
                        .IsUnique()
                        .HasDatabaseName("ix_digests_user_id_digest_type_period_start_period_end");

                    b.ToTable("digests", (string)null);
                });

            modelBuilder.Entity("NewsSummarizer.Core.Entities.DigestItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DigestId")
                        .HasColumnType("uuid")
                        .HasColumnName("digest_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("ReasonSnapshot")
                        .HasColumnType("text")
                        .HasColumnName("reason_snapshot");

                    b.Property<string>("SourceNameSnapshot")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("source_name_snapshot");

                    b.Property<string>("SummarySnapshot")
                        .HasColumnType("text")
                        .HasColumnName("summary_snapshot");

                    b.Property<string>("TitleSnapshot")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_snapshot");

                    b.Property<string>("UrlSnapshot")
                        .HasColumnType("text")
                        .HasColumnName("url_snapshot");

                    b.HasKey("Id")
                        .HasName("pk_digest_items");

                    b.HasIndex("ArticleId")
                        .HasDatabaseName("ix_digest_items_article_id");

                    b.HasIndex("DigestId")
                        .HasDatabaseName("ix_digest_items_digest_id");

                    b.HasIndex("DigestId", "Position")
                        .IsUnique()
                        .HasDatabaseName("ix_digest_items_digest_id_position");

                    b.ToTable("digest_items", (string)null);
                });

            modelBuilder.Entity("NewsSummarizer.Core.Entities.NewsArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CanonicalUrl")
                        .HasColumnType("text")
                        .HasColumnName("canonical_url");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DedupKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("dedup_key");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid?>("DuplicateOfArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("duplicate_of_article_id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<string>("Language")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("language");

                    b.Property<string>("NormalizedTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("normalized_title");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("New")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_news_articles");

                    b.HasIndex("CanonicalUrl")
                        .IsUnique()
                        .HasDatabaseName("ix_news_articles_canonical_url");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("ix_news_articles_content_hash");

                    b.HasIndex("DedupKey")
                        .HasDatabaseName("ix_news_articles_dedup_key");

                    b.HasIndex("DuplicateOfArticleId")
                        .HasDatabaseName("ix_news_articles_duplicate_of_article_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_news_articles_expires_at");

                    b.HasIndex("FetchedAt")
                        .HasDatabaseName("ix_news_articles_fetched_at");

                    b.HasIndex("Language")
                        .HasDatabaseName("ix_news_articles_language");

                    b.HasIndex("NormalizedTitle")
                        .HasDatabaseName("ix_news_articles_normalized_title");

                    b.HasIndex("PublishedAt")
                        .HasDatabaseName("ix_news_articles_published_at");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_news_articles_source_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_news_articles_status");

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasDatabaseName("ix_news_articles_url");

                    b.ToTable("news_articles", (string)null);
                });

            modelBuilder.Entity("NewsSummarizer.Core.Entities.NewsSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultCategories")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("default_categories");

                    b.Property<int>("FetchIntervalMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60)
                        .HasColumnName("fetch_interval_minutes");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.Property<bool>("IsFastSource")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_fast_source");

                    b.Property<string>("Language")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("language");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<DateTimeOffset?>("LastFetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_fetched_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source_type");

                    b.Property<int>("TrustScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(50)
                        .HasColumnName("trust_score");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_news_sources");

                    b.HasIndex("IsEnabled")
                        .HasDatabaseName("ix_news_sources_is_enabled");

                    b.HasIndex("IsFastSource")
                        .HasDatabaseName("ix_news_sources_is_fast_source");

                    b.HasIndex("Language")
                        .HasDatabaseName("ix_news_sources_language");

                    b.HasIndex("Url")
                        .IsUnique()
                        .HasDatabaseName("ix_news_sources_url");

                    b.ToTable("news_sources", (string)null);
                });

            modelBuilder.Entity("NewsSummarizer.Core.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("dedup_key");

                    b.Property<Guid?>("DigestId")
                        .HasColumnType("uuid")
                        .HasColumnName("digest_id");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("error_message");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("MessageSnapshot")
                        .HasColumnType("text")
                        .HasColumnName("message_snapshot");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("notification_type");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("status");

                    b.Property<string>("TitleSnapshot")
                        .HasColumnType("text")
                        .HasColumnName("title_snapshot");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_notifications");

                    b.HasIndex("ArticleId")
                        .HasDatabaseName("ix_notifications_article_id");

                    b.HasIndex("DedupKey")
                        .HasDatabaseName("ix_notifications_dedup_key");

                    b.HasIndex("DigestId")
                        .HasDatabaseName("ix_notifications_digest_id");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_notifications_expires_at");

                    b.HasIndex("NotificationType")
                        .HasDatabaseName("ix_notifications_notification_type");

                    b.HasIndex("SentAt")
                        .HasDatabaseName("ix_notifications_sent_at");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_notifications_user_id");

                    b.HasIndex("UserId", "NotificationType", "DedupKey")
                        .IsUnique()
                        .HasDatabaseName("ix_notifications_user_id_notification_type_dedup_key");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("NewsSummarizer.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("first_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Active")
                        .HasColumnName("status");

                    b.Property<long>("TelegramUserId")
                        .HasColumnType("bigint")
                        .HasColumnName("telegram_user_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("TelegramUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_telegram_user_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("NewsSummarizer.Core.Entities.UserPreferences", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("DailyDigestEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("daily_digest_enabled");

                    b.Property<TimeOnly?>("DailyDigestTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("daily_digest_time");

                    b.Property<string>("EnabledCategories")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("enabled_categories");

                    b.Property<string>("ExcludedTopicsText")
                        .HasColumnType("text")
                        .HasColumnName("excluded_topics_text");

                    b.Property<string>("ImportantTopicsText")
                        .HasColumnType("text")
                        .HasColumnName("important_topics_text");

                    b.Property<int>("MaxItemsPerDigest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("max_items_per_digest");

                    b.Property<bool>("OpportunityDigestEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("opportunity_digest_enabled");

                    b.Property<TimeOnly?>("OpportunityDigestTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("opportunity_digest_time");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Europe/Moscow")
                        .HasColumnName("timezone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("UrgentNotificationsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("urgent_notifications_enabled");

                    b.Property<string>("UrgentTopics")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("urgent_topics");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_preferences");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_preferences_user_id");

                    b.ToTable("user_preferences", (string)null);
                });

            modelBuilder.Entity("NewsSummarizer.Core.Entities.ArticleAiResult", b =>
                {
                    b.HasOne("NewsSummarizer.Core.Entities.NewsArticle", null)
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_ai_results_news_articles_article_id");
                });

            modelBuilder.Entity("NewsSummarizer.Core.Entities.ArticleEmbedding", b =>
                {
                    b.HasOne("NewsSummarizer.Core.Entities.NewsArticle", null)
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_article_embeddings_news_articles_article_id");
                });

            modelBuilder.Entity("NewsSummarizer.Core.Entities.DetailedAnalysis", b =>
                {
                    b.HasOne("NewsSummarizer.Core.Entities.NewsArticle", null)
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_detailed_analyses_news_articles_article_id");

                    b.HasOne("NewsSummarizer.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_detailed_analyses_users_user_id");
                });

            modelBuilder.Entity("NewsSummarizer.Core.Entities.Digest", b =>
                {
                    b.HasOne("NewsSummarizer.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_digests_users_user_id");
                });

            modelBuilder.Entity("NewsSummarizer.Core.Entities.DigestItem", b =>
                {
                    b.HasOne("NewsSummarizer.Core.Entities.NewsArticle", null)
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_digest_items_news_articles_article_id");

                    b.HasOne("NewsSummarizer.Core.Entities.Digest", null)
                        .WithMany()
                        .HasForeignKey("DigestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_digest_items_digests_digest_id");
                });

            modelBuilder.Entity("NewsSummarizer.Core.Entities.NewsArticle", b =>
                {
                    b.HasOne("NewsSummarizer.Core.Entities.NewsArticle", null)
                        .WithMany()
                        .HasForeignKey("DuplicateOfArticleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_news_articles_news_articles_duplicate_of_article_id");

                    b.HasOne("NewsSummarizer.Core.Entities.NewsSource", null)
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_news_articles_news_sources_source_id");
                });

            modelBuilder.Entity("NewsSummarizer.Core.Entities.Notification", b =>
                {
                    b.HasOne("NewsSummarizer.Core.Entities.NewsArticle", null)
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notifications_news_articles_article_id");

                    b.HasOne("NewsSummarizer.Core.Entities.Digest", null)
                        .WithMany()
                        .HasForeignKey("DigestId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_notifications_digests_digest_id");

                    b.HasOne("NewsSummarizer.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");
                });

            modelBuilder.Entity("NewsSummarizer.Core.Entities.UserPreferences", b =>
                {
                    b.HasOne("NewsSummarizer.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_preferences_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
